version: "2"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres_password
  redis:
    image: redis
  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile.dev

    volumes:
      - /usr/app/node_modules
      - ./worker:/usr/app

    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev

    volumes:
      - /usr/app/node_modules
      - ./server:/usr/app

    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DATABASE=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres_password
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev

    volumes:
      - /usr/app/node_modules
      - ./client:/usr/app
    environment:
      - WDS_SOCKET_PORT=0
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev

    volumes:
      - /usr/app/node_modules
      - ./nginx:/usr/app

    ports:
      - 3050:80

